<a href="https://colab.research.google.com/github/RodrigoLima82/Tensorflow2.0/blob/master/Introdu%C3%A7%C3%A3o_TensorFlow_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 1.X




### Instalando o TensorFlow 1.X



In [1]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.2MB 42kB/s 
     |████████████████████████████████| 368kB 42.1MB/s 
     |████████████████████████████████| 3.2MB 44.8MB/s 
ERROR: tensorflow 1.15.0 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: tensorflow 1.15.0 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 1.13.0 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0


In [2]:
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

In [3]:
tf.__version__

'1.13.1'

### Constantes

#### Definindo uma constante

In [0]:
# Definindo uma constante no TensorFlow
tensor = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [0]:
# Se uma sessão não for inicializada, não podemos acessar os valores da constante
tensor.eval()

#### Acessando os valores de uma constante

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
tensor_value = session.run(tensor)

In [10]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variáveis

#### Definindo uma variável

In [11]:
# Definindo uma variável no TensorFlow
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [12]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [0]:
# Se uma sessão na for inicializada, não podemos acessar os valores das variáveis
variable.eval()

#### Acessando os valores de uma variável

In [0]:
# Inicializando uma sessão
session = tf.Session()

In [0]:
# Inicializando TODAS as variáveis de uma seção
session.run(tf.global_variables_initializer())

In [16]:
# Executando o método eval no ambiente com a sessão inicializada para conseguir buscar os valores
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Instalando o TensorFlow 2.0

In [17]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 51kB/s 
     |████████████████████████████████| 3.0MB 35.5MB/s 
     |████████████████████████████████| 419kB 53.8MB/s 
  Found existing installation: tensorflow-gpu 1.13.1
    Uninstalling tensorflow-gpu-1.13.1:
      Successfully uninstalled tensorflow-gpu-1.13.1


In [0]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.0.0-alpha0'

### Constantes

#### Definindo uma constante

In [0]:
# Definindo uma constante no TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [6]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [7]:
# Acessando as dimensões de um tensor
tensor_20.shape

TensorShape([2, 2])

#### Acessando os valores de uma constante

In [8]:
# Acessando os valores de um tensor com o numpy e sem precisar de uma sessão
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
# Podemos converter um numpy array para um tensor do TensorFlow
numpy_tensor = np.array([[23,  4], [32, 51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [11]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variáveis

#### Definindo uma variável

In [12]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Acessando os valores de uma variável

In [13]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Alterando um valor específico de uma variável

In [14]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [15]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operações com tensores

In [16]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=27, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Adição entre um escalar e um tensor

In [17]:
tensor + 2

<tf.Tensor: id=30, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicação entre um escalar e um tensor

In [18]:
tensor * 5

<tf.Tensor: id=33, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Usando funções do numpy nos tensores do TensorFlow

In [19]:
# Obtendo o quadrado de todos os membros de um tensor
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [20]:
# Obtendo a raiz quadrada de todos os membros de um tensor
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product (produto escalar) entre dois tensores

In [21]:
tensor

<tf.Tensor: id=27, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [22]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [23]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings no TensorFlow 2.0

In [24]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=43, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operações simples com strings

In [25]:
tf.strings.length(tf_string)

<tf.Tensor: id=45, shape=(), dtype=int32, numpy=10>

In [26]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=50, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Armazenando arrays (vetores) de strings

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [28]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
